name: Azure Stream Anlytics Job Deployment
description:
  updates azure streaming analytics job wrapping with a stop and start
author: Shawn Cicoria

branding:
  icon: 'activity'
  color: 'green'

inputs:
  cmd:
    description: The command to run
    required: true
  job-name:
    description: The name of the job to update
    required: true
  resource-group:
    description: The resource group of the job
    required: true
  subscription:
    description: The subscription of the job
    required: true
  job-query:
    description: The query to update the job with
    required: false
  restart:
    description: restart the job
    required: false
  start-time:
    description: instead of last update time
    required: false
  log-level:
    description: The log level - verbose, info, warning, error
    required: false
    default: warning

outputs:
  job-start-status:
    description: streaming job information

runs:
  using: node20
  main: dist/index.js
