# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: list all the tasks
    cmds:
      - task --list-all
    silent: true

  act:
    cmds:
      - act -W ./.github/workflows/local-run.yml

  local:test:
    cmds:
      - local-action . src/index.ts .env
